### ISSUE TITLE
melt_duplex errors

### ISSUE THREAD

**Issue by jil24** [ggirelli/oligo-melting#1]
Trying out melt_duplex doesn't seem to work as-is.

`python3 melt_duplex -t DNA:RNA gatctgtcaccacataatta`
yields
```
Traceback (most recent call last):
  File "melt_duplex", line 215, in <module>
    else: run_seq(args.seq[0], **data)
  File "melt_duplex", line 161, in run_seq
    output = OligoMelt.XDuplex.calc_tm(**kwargs)
```

I figured XDuplex was a typo; changing it to
`output = OligoMelt.XDuplex.calc_tm(**kwargs)`
lets the script generate appropriate output, but then throw an exception later

```
Traceback (most recent call last):
  File "melt_duplex", line 215, in <module>
    else: run_seq(args.seq[0], **data)
  File "melt_duplex", line 164, in run_seq
    print_header(fasta_like = fasta_like, **kwargs)
NameError: name 'fasta_like' is not defined
```

**Comment by ggirelli** [comment]
Hi @jil24, and thank you for reporting this bug! I fixed it in the dev branch but have not had time in the past few months to wrap it up as a version release. In the coming months, I will release a brand new version of `oligo-melting` with some additional features. In the meantime, I would recommend installing the dev branch with the following:
```
git clone https://github.com/ggirelli/oligo-melting/ --branch dev
cd oligo-melting
pip3 install --user -e .
```
This code will install the package only for your user. You can do this in a conda environment if you prefer. Then, your command would become (notice the capital `T`):
`melt_duplex -T DNA:RNA gatctgtcaccacataatta`
Let me know if this works for you!

**Comment by ggirelli** [comment]
As I have not had the chance to wrap up the v3.0.0 yet, I am releasing a new point version (v2.0.2) that fixes this typo. Apologies for the long wait.
